# Generated by Django 3.2.7 on 2021-09-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_ticket_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Under Consideration', 'Under Consideration'), ('Reviewed', 'Reviewed'), ('Freezed', 'Freezed')], default='Under Consideration', max_length=30),
        ),
    ]
