# Generated by Django 3.2.7 on 2021-09-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20210922_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Write here', max_length=250),
        ),
    ]
