# Generated by Django 3.2.7 on 2021-09-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_comment_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_comment']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='name_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='position',
            new_name='position_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='text_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='ticket',
            new_name='ticket_comment',
        ),
    ]
