# Generated by Django 3.2.7 on 2021-09-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
