# Generated by Django 3.2.7 on 2021-09-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_alter_ticket_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default=123456),
            preserve_default=False,
        ),
    ]
