# Generated by Django 3.2.7 on 2021-09-23 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_comment', models.CharField(max_length=50)),
                ('position_comment', models.CharField(max_length=50)),
                ('text_comment', models.TextField(blank=True, max_length=250)),
                ('created_comment', models.DateTimeField(auto_now_add=True)),
                ('ticket_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='support.ticket')),
            ],
            options={
                'ordering': ['created_comment'],
            },
        ),
    ]
