# Generated by Django 3.2.7 on 2021-09-23 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0018_alter_comment_ticket_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ticket_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='support.ticket'),
        ),
    ]
